---
title: "Lieve_Debugs"
author: "Lieve Verschelde & Marijke Thoonen"
date: "2025-03-17"
output: html_document
---

## Load required packages

### With the library googlesheets4, Rstudio has access to the dataset

```{r packages, include=FALSE}
library(lubridate)
library(dplyr)
library(tidyverse)

# to load google sheet
library(googlesheets4) 

# to name columns
library(janitor)  
```

## Set working directory

Sets the working directory in R to the folder containing the currently active script

```{r working directory}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

## Load raw data

```{r}
sheet_url <- "https://docs.google.com/spreadsheets/d/1uJ7rvQBkw0_-e2dsiBlX2NJcrCcfEFqC-ZvEV0RwNVg/edit"
groundbeetle.data <- read_sheet(sheet_url, col_names = FALSE)

```

## Edit and finetune raw dataset

```{r}
# remove first row
groundbeetle.data <- groundbeetle.data %>% slice(-1) 
# make first row header
groundbeetle.data <- groundbeetle.data %>% row_to_names(row_number = 1)

# convert column dates to date type
groundbeetle.data$Ophaaldatum <- ymd(groundbeetle.data$Ophaaldatum) 
  # 1 date failed, sample without label

# convert data to a data set, easier to make models
groundbeetle.data <- as.data.frame(groundbeetle.data) 

# View dataset
View(groundbeetle.data)
```

## Convert datatypes

```{r}
# convert column of sample numbers to character
groundbeetle.data$Staalnummer <- as.character(groundbeetle.data$Staalnummer)


# View datatypes of dataset
glimpse(groundbeetle.data)

# Identify remainder columns with 'list' type (all species)
list_columns <- sapply(groundbeetle.data, is.list)

# Conversion
groundbeetle.data[, list_columns] <- lapply(groundbeetle.data[, list_columns], function(column) {
  # Convert NULL to NA
  column <- sapply(column, function(x) if (is.null(x)) NA else x)
  # Apply conversion to numeric
  column <- as.numeric(unlist(column))
})

# select species columns
species_columns <- names(groundbeetle.data)[sapply(groundbeetle.data, is.numeric)]

# replace all NA with 0 in species columns
groundbeetle.data <- groundbeetle.data %>%
  mutate(across(all_of(species_columns), ~ ifelse(is.na(.), 0, .)))


## View datatype after conversion
sapply(groundbeetle.data, class)
View(groundbeetle.data)
```

# Link traitlists

```{r}
# Load txt files
species_taxon_path <- "C:/Users/lieve/OneDrive/Documenten/Academiejaar_2024_2025/thesis/Data_analyse/Github/Thesis_Lieve/Data_raw/Arthropoda_Traits_Logghe/taxon.txt"
species_habitats_path <- "C:/Users/lieve/OneDrive/Documenten/Academiejaar_2024_2025/thesis/Data_analyse/Github/Thesis_Lieve/Data_raw/Arthropoda_Traits_Logghe/description.txt"
species_measurements_path <-"C:/Users/lieve/OneDrive/Documenten/Academiejaar_2024_2025/thesis/Data_analyse/Github/Thesis_Lieve/Data_raw/Arthropoda_Traits_Logghe/measurementorfacts.txt"

species_taxon <- read.table(species_taxon_path, header = TRUE, sep = "\t")
species_habitat <- read.table(species_habitats_path, header = TRUE, sep = "\t" )
species_measurements <- read.table(species_measurements_path, header = TRUE, sep = "\t" )

view(species_taxon)
view(species_habitat)
view(species_measurements)
```

# filter datasets (Logghe), compose traitlist dataset
```{r}
# Get groundbeetle species from data set (column (5-58))
groundbeetle_species <- colnames(groundbeetle.data)[5:58]
view(groundbeetle_species)

# Get groundbeetle species occuring in own dataset (groundbeetle.data) from taxon dataset (filter)
species_filtered <- subset(species_taxon, scientificName %in% groundbeetle_species)
groundbeetle_taxon <- species_filtered

# View result of filtered list
View(groundbeetle_taxon) # 53 entries, only 1 species not included (Trichocellus placidus changed name to Dicheirotrichus placidus)
difference <- setdiff(groundbeetle_species,groundbeetle_taxon$scientificName)
View(difference) # subspecies Carabus violaceus purpurascens lacking

# compare id's of columns, if TRUE, remove excess column
identical(groundbeetle_taxon$id, groundbeetle_taxon$taxonID)
groundbeetle_taxon$taxonID <- NULL
view(groundbeetle_taxon)

species_measurements_sorted <- species_measurements %>%
  pivot_wider(
    names_from = measurementType, 
    values_from = c(measurementValue, measurementUnit)
  )
View(species_measurements_sorted)

# merge taxon and measurements in one dataset
traitlist_result <- merge(groundbeetle_taxon, species_measurements_sorted, by = "id")
view(traitlist_result)

# check dataset types
glimpse(groundbeetle_taxon)
glimpse(traitlist_result)

```
